// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_authentication.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EXFN_Authentication module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ClientConfiguration_NewEditBuilder(
		exfn_authentication.proxies.ClientConfiguration _clientConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.ACT_ClientConfiguration_NewEdit");
		builder = builder.withParam("ClientConfiguration", _clientConfiguration);
		return builder;
	}

	public static void aCT_ClientConfiguration_NewEdit(
		IContext context,
		exfn_authentication.proxies.ClientConfiguration _clientConfiguration
	)
	{
		aCT_ClientConfiguration_NewEditBuilder(
				_clientConfiguration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetRefreshSessionBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.DS_GetRefreshSession");
		return builder;
	}

	public static exfn_authentication.proxies.RefreshSession dS_GetRefreshSession(IContext context)
	{
		Object result = dS_GetRefreshSessionBuilder().execute(context);
		return result == null ? null : exfn_authentication.proxies.RefreshSession.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder errorHandling_ConsumedODataServiceBuilder(
		system.proxies.HttpResponse _httpResponse
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.ErrorHandling_ConsumedODataService");
		builder = builder.withParam("httpResponse", _httpResponse);
		return builder;
	}

	public static java.lang.String errorHandling_ConsumedODataService(
		IContext context,
		system.proxies.HttpResponse _httpResponse
	)
	{
		Object result = errorHandling_ConsumedODataServiceBuilder(
				_httpResponse
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getClientIdBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.GetClientId");
		return builder;
	}

	public static java.lang.String getClientId(IContext context)
	{
		Object result = getClientIdBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder headers_ConsumedODataServiceBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.Headers_ConsumedODataService");
		return builder;
	}

	public static java.util.List<system.proxies.HttpHeader> headers_ConsumedODataService(IContext context)
	{
		Object result = headers_ConsumedODataServiceBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> system.proxies.HttpHeader.initialize(context, obj));
	}
	/**
	 * Microflow to navigate to the client configuration page for initial setup before visualizing the Mendix App.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder nav_ClientConfiguration_OverviewBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.Nav_ClientConfiguration_Overview");
		return builder;
	}

	/**
	 * Microflow to navigate to the client configuration page for initial setup before visualizing the Mendix App.
	 */
	public static void nav_ClientConfiguration_Overview(IContext context)
	{
		nav_ClientConfiguration_OverviewBuilder().execute(context);
	}
	/**
	 * Microflow to retreive all the saved client configurations for viewing and modifications.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_ActiveClientConfiguration_GetBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.SUB_ActiveClientConfiguration_Get");
		return builder;
	}

	/**
	 * Microflow to retreive all the saved client configurations for viewing and modifications.
	 */
	public static exfn_authentication.proxies.ClientConfiguration sUB_ActiveClientConfiguration_Get(IContext context)
	{
		Object result = sUB_ActiveClientConfiguration_GetBuilder().execute(context);
		return result == null ? null : exfn_authentication.proxies.ClientConfiguration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_GetDefaultClientConfigurationBuilder(
		exfn_authentication.proxies.ClientConfiguration _actualClientConfiguration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.SUB_GetDefaultClientConfiguration");
		builder = builder.withParam("ActualClientConfiguration", _actualClientConfiguration);
		return builder;
	}

	public static exfn_authentication.proxies.ClientConfiguration sUB_GetDefaultClientConfiguration(
		IContext context,
		exfn_authentication.proxies.ClientConfiguration _actualClientConfiguration
	)
	{
		Object result = sUB_GetDefaultClientConfigurationBuilder(
				_actualClientConfiguration
			)
			.execute(context);
		return result == null ? null : exfn_authentication.proxies.ClientConfiguration.initialize(context, (IMendixObject) result);
	}
	/**
	 * Microflow to get the token from UMC.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Token_GetBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_Authentication.SUB_Token_Get");
		return builder;
	}

	/**
	 * Microflow to get the token from UMC.
	 */
	public static exfn_authentication.proxies.Token sUB_Token_Get(IContext context)
	{
		Object result = sUB_Token_GetBuilder().execute(context);
		return result == null ? null : exfn_authentication.proxies.Token.initialize(context, (IMendixObject) result);
	}
}
