// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_servicelayer.proxies;

public class RF_RequestParameters implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rF_RequestParametersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXFN_ServiceLayer.RF_RequestParameters";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		URL("URL"),
		OdataFilter("OdataFilter"),
		Top("Top"),
		Skip("Skip"),
		OrderBy("OrderBy"),
		FunctionFilter("FunctionFilter");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RF_RequestParameters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RF_RequestParameters(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rF_RequestParametersMendixObject)
	{
		if (rF_RequestParametersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, rF_RequestParametersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.rF_RequestParametersMendixObject = rF_RequestParametersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static exfn_servicelayer.proxies.RF_RequestParameters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new exfn_servicelayer.proxies.RF_RequestParameters(context, mendixObject);
	}

	public static exfn_servicelayer.proxies.RF_RequestParameters load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return exfn_servicelayer.proxies.RF_RequestParameters.initialize(context, mendixObject);
	}

	/**
	 * @return value of URL
	 */
	public final java.lang.String getURL()
	{
		return getURL(getContext());
	}

	/**
	 * @param context
	 * @return value of URL
	 */
	public final java.lang.String getURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.URL.toString());
	}

	/**
	 * Set value of URL
	 * @param url
	 */
	public final void setURL(java.lang.String url)
	{
		setURL(getContext(), url);
	}

	/**
	 * Set value of URL
	 * @param context
	 * @param url
	 */
	public final void setURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.URL.toString(), url);
	}

	/**
	 * @return value of OdataFilter
	 */
	public final java.lang.String getOdataFilter()
	{
		return getOdataFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of OdataFilter
	 */
	public final java.lang.String getOdataFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OdataFilter.toString());
	}

	/**
	 * Set value of OdataFilter
	 * @param odatafilter
	 */
	public final void setOdataFilter(java.lang.String odatafilter)
	{
		setOdataFilter(getContext(), odatafilter);
	}

	/**
	 * Set value of OdataFilter
	 * @param context
	 * @param odatafilter
	 */
	public final void setOdataFilter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String odatafilter)
	{
		getMendixObject().setValue(context, MemberNames.OdataFilter.toString(), odatafilter);
	}

	/**
	 * @return value of Top
	 */
	public final java.lang.Integer getTop()
	{
		return getTop(getContext());
	}

	/**
	 * @param context
	 * @return value of Top
	 */
	public final java.lang.Integer getTop(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Top.toString());
	}

	/**
	 * Set value of Top
	 * @param top
	 */
	public final void setTop(java.lang.Integer top)
	{
		setTop(getContext(), top);
	}

	/**
	 * Set value of Top
	 * @param context
	 * @param top
	 */
	public final void setTop(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer top)
	{
		getMendixObject().setValue(context, MemberNames.Top.toString(), top);
	}

	/**
	 * @return value of Skip
	 */
	public final java.lang.Integer getSkip()
	{
		return getSkip(getContext());
	}

	/**
	 * @param context
	 * @return value of Skip
	 */
	public final java.lang.Integer getSkip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Skip.toString());
	}

	/**
	 * Set value of Skip
	 * @param skip
	 */
	public final void setSkip(java.lang.Integer skip)
	{
		setSkip(getContext(), skip);
	}

	/**
	 * Set value of Skip
	 * @param context
	 * @param skip
	 */
	public final void setSkip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer skip)
	{
		getMendixObject().setValue(context, MemberNames.Skip.toString(), skip);
	}

	/**
	 * @return value of OrderBy
	 */
	public final java.lang.String getOrderBy()
	{
		return getOrderBy(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderBy
	 */
	public final java.lang.String getOrderBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderBy.toString());
	}

	/**
	 * Set value of OrderBy
	 * @param orderby
	 */
	public final void setOrderBy(java.lang.String orderby)
	{
		setOrderBy(getContext(), orderby);
	}

	/**
	 * Set value of OrderBy
	 * @param context
	 * @param orderby
	 */
	public final void setOrderBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String orderby)
	{
		getMendixObject().setValue(context, MemberNames.OrderBy.toString(), orderby);
	}

	/**
	 * @return value of FunctionFilter
	 */
	public final java.lang.String getFunctionFilter()
	{
		return getFunctionFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of FunctionFilter
	 */
	public final java.lang.String getFunctionFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FunctionFilter.toString());
	}

	/**
	 * Set value of FunctionFilter
	 * @param functionfilter
	 */
	public final void setFunctionFilter(java.lang.String functionfilter)
	{
		setFunctionFilter(getContext(), functionfilter);
	}

	/**
	 * Set value of FunctionFilter
	 * @param context
	 * @param functionfilter
	 */
	public final void setFunctionFilter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String functionfilter)
	{
		getMendixObject().setValue(context, MemberNames.FunctionFilter.toString(), functionfilter);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rF_RequestParametersMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final exfn_servicelayer.proxies.RF_RequestParameters that = (exfn_servicelayer.proxies.RF_RequestParameters) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
