// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_servicelayer.proxies;

public class UIApplications implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject uIApplicationsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXFN_ServiceLayer.UIApplications";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UIApplications_UIApplicationsPerPlantItem("EXFN_ServiceLayer.UIApplications_UIApplicationsPerPlantItem");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UIApplications(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UIApplications(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject uIApplicationsMendixObject)
	{
		if (uIApplicationsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, uIApplicationsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.uIApplicationsMendixObject = uIApplicationsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static exfn_servicelayer.proxies.UIApplications initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new exfn_servicelayer.proxies.UIApplications(context, mendixObject);
	}

	public static exfn_servicelayer.proxies.UIApplications load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return exfn_servicelayer.proxies.UIApplications.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UIApplications_UIApplicationsPerPlantItem
	 */
	public final exfn_servicelayer.proxies.UIApplicationsPerPlantItem getUIApplications_UIApplicationsPerPlantItem() throws com.mendix.core.CoreException
	{
		return getUIApplications_UIApplicationsPerPlantItem(getContext());
	}

	/**
	 * @param context
	 * @return value of UIApplications_UIApplicationsPerPlantItem
	 * @throws com.mendix.core.CoreException
	 */
	public final exfn_servicelayer.proxies.UIApplicationsPerPlantItem getUIApplications_UIApplicationsPerPlantItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		exfn_servicelayer.proxies.UIApplicationsPerPlantItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UIApplications_UIApplicationsPerPlantItem.toString());
		if (identifier != null) {
			result = exfn_servicelayer.proxies.UIApplicationsPerPlantItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UIApplications_UIApplicationsPerPlantItem
	 * @param uiapplications_uiapplicationsperplantitem
	 */
	public final void setUIApplications_UIApplicationsPerPlantItem(exfn_servicelayer.proxies.UIApplicationsPerPlantItem uiapplications_uiapplicationsperplantitem)
	{
		setUIApplications_UIApplicationsPerPlantItem(getContext(), uiapplications_uiapplicationsperplantitem);
	}

	/**
	 * Set value of UIApplications_UIApplicationsPerPlantItem
	 * @param context
	 * @param uiapplications_uiapplicationsperplantitem
	 */
	public final void setUIApplications_UIApplicationsPerPlantItem(com.mendix.systemwideinterfaces.core.IContext context, exfn_servicelayer.proxies.UIApplicationsPerPlantItem uiapplications_uiapplicationsperplantitem)
	{
		if (uiapplications_uiapplicationsperplantitem == null) {
			getMendixObject().setValue(context, MemberNames.UIApplications_UIApplicationsPerPlantItem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UIApplications_UIApplicationsPerPlantItem.toString(), uiapplications_uiapplicationsperplantitem.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return uIApplicationsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final exfn_servicelayer.proxies.UIApplications that = (exfn_servicelayer.proxies.UIApplications) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
