// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_servicelayer.proxies;

public class UIApplication implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject uIApplicationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXFN_ServiceLayer.UIApplication";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UIAppName("UIAppName"),
		UIAppTitle("UIAppTitle"),
		_Type("_Type"),
		UIAppUrl("UIAppUrl"),
		UIApplication_UIApplications("EXFN_ServiceLayer.UIApplication_UIApplications");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UIApplication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UIApplication(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject uIApplicationMendixObject)
	{
		if (uIApplicationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, uIApplicationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.uIApplicationMendixObject = uIApplicationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static exfn_servicelayer.proxies.UIApplication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new exfn_servicelayer.proxies.UIApplication(context, mendixObject);
	}

	public static exfn_servicelayer.proxies.UIApplication load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return exfn_servicelayer.proxies.UIApplication.initialize(context, mendixObject);
	}

	/**
	 * @return value of UIAppName
	 */
	public final java.lang.String getUIAppName()
	{
		return getUIAppName(getContext());
	}

	/**
	 * @param context
	 * @return value of UIAppName
	 */
	public final java.lang.String getUIAppName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UIAppName.toString());
	}

	/**
	 * Set value of UIAppName
	 * @param uiappname
	 */
	public final void setUIAppName(java.lang.String uiappname)
	{
		setUIAppName(getContext(), uiappname);
	}

	/**
	 * Set value of UIAppName
	 * @param context
	 * @param uiappname
	 */
	public final void setUIAppName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uiappname)
	{
		getMendixObject().setValue(context, MemberNames.UIAppName.toString(), uiappname);
	}

	/**
	 * @return value of UIAppTitle
	 */
	public final java.lang.String getUIAppTitle()
	{
		return getUIAppTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of UIAppTitle
	 */
	public final java.lang.String getUIAppTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UIAppTitle.toString());
	}

	/**
	 * Set value of UIAppTitle
	 * @param uiapptitle
	 */
	public final void setUIAppTitle(java.lang.String uiapptitle)
	{
		setUIAppTitle(getContext(), uiapptitle);
	}

	/**
	 * Set value of UIAppTitle
	 * @param context
	 * @param uiapptitle
	 */
	public final void setUIAppTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uiapptitle)
	{
		getMendixObject().setValue(context, MemberNames.UIAppTitle.toString(), uiapptitle);
	}

	/**
	 * @return value of _Type
	 */
	public final java.lang.String get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final java.lang.String get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Type.toString());
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(java.lang.String _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._Type.toString(), _type);
	}

	/**
	 * @return value of UIAppUrl
	 */
	public final java.lang.String getUIAppUrl()
	{
		return getUIAppUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of UIAppUrl
	 */
	public final java.lang.String getUIAppUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UIAppUrl.toString());
	}

	/**
	 * Set value of UIAppUrl
	 * @param uiappurl
	 */
	public final void setUIAppUrl(java.lang.String uiappurl)
	{
		setUIAppUrl(getContext(), uiappurl);
	}

	/**
	 * Set value of UIAppUrl
	 * @param context
	 * @param uiappurl
	 */
	public final void setUIAppUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uiappurl)
	{
		getMendixObject().setValue(context, MemberNames.UIAppUrl.toString(), uiappurl);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UIApplication_UIApplications
	 */
	public final exfn_servicelayer.proxies.UIApplications getUIApplication_UIApplications() throws com.mendix.core.CoreException
	{
		return getUIApplication_UIApplications(getContext());
	}

	/**
	 * @param context
	 * @return value of UIApplication_UIApplications
	 * @throws com.mendix.core.CoreException
	 */
	public final exfn_servicelayer.proxies.UIApplications getUIApplication_UIApplications(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		exfn_servicelayer.proxies.UIApplications result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UIApplication_UIApplications.toString());
		if (identifier != null) {
			result = exfn_servicelayer.proxies.UIApplications.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UIApplication_UIApplications
	 * @param uiapplication_uiapplications
	 */
	public final void setUIApplication_UIApplications(exfn_servicelayer.proxies.UIApplications uiapplication_uiapplications)
	{
		setUIApplication_UIApplications(getContext(), uiapplication_uiapplications);
	}

	/**
	 * Set value of UIApplication_UIApplications
	 * @param context
	 * @param uiapplication_uiapplications
	 */
	public final void setUIApplication_UIApplications(com.mendix.systemwideinterfaces.core.IContext context, exfn_servicelayer.proxies.UIApplications uiapplication_uiapplications)
	{
		if (uiapplication_uiapplications == null) {
			getMendixObject().setValue(context, MemberNames.UIApplication_UIApplications.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UIApplication_UIApplications.toString(), uiapplication_uiapplications.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return uIApplicationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final exfn_servicelayer.proxies.UIApplication that = (exfn_servicelayer.proxies.UIApplication) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
