// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {boolean} zoomIn
 * @returns {Promise.<void>}
 */
export async function JS_Gantt_Zoom(zoomIn) {
	// BEGIN USER CODE
	 const zoomEvent = new CustomEvent("siemens-gantt-zoom", {
        detail: {
            zoomIn: zoomIn
        }
    });
    window.dispatchEvent(zoomEvent);
	// END USER CODE
}
