// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JS_SearchTextBox_Filter() {
	// BEGIN USER CODE
	var input, filter, ul, li, a, i, txtValue;
    input = document.querySelector('.mx-name-textBox1').firstChild;
    filter = input.value.toUpperCase();
    ul = document.querySelector('.mx-name-navigationTree1 .navbar-inner').firstChild;
    li = ul.getElementsByTagName("li");
	//Skip first element: Configuration
    for (i = 1; i < li.length; i++) {
		if (li[i].className) continue;
        a = li[i].getElementsByTagName("a")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1 || li[i].className.indexOf("alwaysshow") > -1) {
            li[i].style.display = "list-item";
        } else {
            li[i].style.display = "none";
        }
    }
	// END USER CODE
}
