// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This will remove all children for the node in the widget. The widget will then trigger the node datasource and set the LoadType to "NodeOrRoot" and reset the offset when applicable.
 * 
 * What you load at this point is up to you. You can load the direct children only or choose to reload the entire tree.
 * @param {string} widgetName - You can find the widget name under the common tab of the widget
 * @param {Big} parentNodeId
 * @returns {Promise.<void>}
 */
export async function JS_Tree_ReloadChildNodes(widgetName, parentNodeId) {
	// BEGIN USER CODE
	if (!widgetName || !parentNodeId) {
		return;
	}
	window.dispatchEvent(new CustomEvent("advanced_tree_widget", { detail: { widgetName, action: "reloadNodeChildren", nodeId: +parentNodeId.toString() } }));
	// END USER CODE
}
