// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} widgetName - You can find the widget name under the common tab of the widget
 * @param {Big} nodeId
 * @returns {Promise.<void>}
 */
export async function JS_Tree_RemoveNodeFromWidget(widgetName, nodeId) {
	// BEGIN USER CODE
	if (!widgetName || !nodeId) {
		return;
	}
	window.dispatchEvent(new CustomEvent("advanced_tree_widget", { detail: { widgetName, action: "removeNode", nodeId: +nodeId.toString() } }));
	// END USER CODE
}
