// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function isLogEnabled() {
	if(window.LogEnabled != undefined) return window.LogEnabled;
	var constants = mx.session.getConstants();
	var logEnabled = constants.find(function(element, index) {
        return element.name == 'OpcenterEXFN_DISW_DesignSystem.LogEnabled';
	});
	window.LogEnabled = logEnabled ? logEnabled.value : false;
	return window.LogEnabled;
}
// END EXTRA CODE

/**
 * @param {string} flowName
 * @returns {Promise.<void>}
 */
export async function LogEnd(flowName) {
	// BEGIN USER CODE
	if(!isLogEnabled()) return;
	var date = new Date();
	var dateString = new Date(date.getTime() - (date.getTimezoneOffset() * 60000 )).toISOString();
	console.warn(dateString + ' - End '+flowName);
	// END USER CODE
}
