// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function isLogEnabled() {
	if(window.LogEnabled != undefined) return window.LogEnabled;
	var constants = mx.session.getConstants();
	var logEnabled = constants.find(function(element, index) {
        return element.name == 'OpcenterEXFN_DISW_DesignSystem.LogEnabled';
	});
	window.LogEnabled = logEnabled ? logEnabled.value : false;
	return window.LogEnabled;
}
// END EXTRA CODE

/**
 * @param {string} message
 * @param {MxObject} obj
 * @param {string} attributesCommaSeparated
 * @returns {Promise.<void>}
 */
export async function LogObj(message, obj, attributesCommaSeparated) {
	// BEGIN USER CODE
	if(!isLogEnabled()) return;
	var attributes = attributesCommaSeparated.split(',');
	var objNew = {};
	if(attributes.length > 1) {		
		for(var j=0;j<attributes.length;j++) {
			//var attrs = mxobject.getAttributes();
			var value = obj.get(attributes[j]);
			objNew[attributes[j]] = value;
		}
		console.warn(message, objNew);
	}
	else {
		var value = obj.get(attributes[0]);
		console.warn(message, value);
	}
	// END USER CODE
}
