// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function _removeClass(elementClass, classToRemove) {
	const element = document.querySelector("." + elementClass);
	if(element && element.classList.contains(classToRemove)) {
	   element.classList.remove(classToRemove);
	}
}
// END EXTRA CODE

/**
 * @param {string} elementClass
 * @param {string} classToRemove
 * @param {Big} delay
 * @returns {Promise.<void>}
 */
export async function RemoveClass(elementClass, classToRemove, delay) {
	// BEGIN USER CODE
	return new Promise((resolve, reject) => {
        setTimeout(() => {
            _removeClass(elementClass, classToRemove, delay);       
        }, Number(delay));
        resolve();
	});
	// END USER CODE
}
