// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function _SetPosition(elementToMoveClass, elementParentClass) {
	const elementToMove = document.querySelector("." + elementToMoveClass);
	const elementParent = document.querySelector("." + elementParentClass);
	let rect = elementParent.getBoundingClientRect();
	if(elementToMove && elementParent) {
	   elementToMove.style.position = 'fixed';
       var left = Math.floor(rect.x) - 130;
	   var top = Math.floor(rect.y + rect.height);
	   var screenHeight = document.body.clientHeight;
	   var clientHeight = elementToMove.clientHeight;

	   if(clientHeight == 0){
	     clientHeight = 164;
       }
	   var elementToMoveCanBePlaceBelowElementParent = top + clientHeight <= screenHeight;
 	   if(!elementToMoveCanBePlaceBelowElementParent) {
		  top = Math.floor(rect.y) - clientHeight;
	   }
	   elementToMove.style.top = top + 'px';
	   elementToMove.style.left = left + 'px';
	}
}
// END EXTRA CODE

/**
 * @param {string} elementToMoveClass
 * @param {string} elementParentClass
 * @param {Big} delay
 * @returns {Promise.<void>}
 */
export async function SetPositionBelowOrAboveOtherElement(elementToMoveClass, elementParentClass, delay) {
	// BEGIN USER CODE
	return new Promise((resolve, reject) => {
        setTimeout(() => {
            _SetPosition(elementToMoveClass, elementParentClass);       
        }, Number(delay));
        resolve();
	});
	// END USER CODE
}
