// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
const closeIcon = `<svg viewBox="0 0 16 16">
	<polygon points="15.878 .858 15.171 .151 8.026 7.293 .829 .099 .122 .806 7.318 8 .122 15.194 .829 15.901 8.026 8.707 15.171 15.85 15.878 15.143 8.733 8 15.878 .858" fill="#ffff"/>
</svg>`;

function createElement({elemTag, attrs, classList, childNodes}) {
	const elem = document.createElement(elemTag);
	if (classList){
		elem.classList.add(...classList);
	}
	if (attrs) {
		Object.keys(attrs).forEach(attr =>{ elem[attr] = attrs[attr]});
	}
	if (childNodes) {
		elem.append(...childNodes);
	}
	return elem;
}

function createUserAvatar() {
	const svgIcon = `<svg focusable="false" viewBox="0 0 24 24">
		<path fill="#464646" d="M12,10.5c2.2,0,4-2.9,4-5.3C16,2.9,14.2,1,12,1S8,2.9,8,5.2C8,7.6,9.8,10.5,12,10.5z M12,2c1.7,0,3,1.4,3,3.2 c0,1.9-1.5,4.3-3,4.3S9,7.1,9,5.2C9,3.4,10.3,2,12,2z"></path>
		<path fill="#464646" d="M16.7,11.1l-0.3-0.1l-0.2,0.2c-2.6,1.8-5.8,1.8-8.4,0l-0.2-0.2l-0.3,0.1c-2,1-3.3,2.8-3.3,4.8V24h16v-8.1 C20,13.9,18.7,12,16.7,11.1z M19,23h-2v-6h-1v6H8v-6H7v6H5v-7.1c0-1.5,0.9-3,2.5-3.8c2.8,1.9,6.2,1.9,9.1,0c1.5,0.8,2.5,2.3,2.5,3.8 V23z"></path>
	</svg>`;

	return createElement({elemTag: "div", classList: ['user-icon'], attrs: {innerHTML: svgIcon}});
}

function createDockActions(dockUserPropertiesLabel, undockUserPropertiesLabel) {
	const svgDockIcon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
		<path d="M13,8H12v3H5V4H8V3H4V6H1v9h9V12h3ZM9,14H2V7H4v5H9Z"  fill="#ffb900"/>
		<polygon points="14.854 1.854 14.146 1.146 11 4.293 11 2 10 2 10 6 14 6 14 5 11.707 5 14.854 1.854" fill="#ffb900"/>
	</svg>`;
	
	const svgUndockIcon = `<svg viewBox="0 0 16 16">
		<path d="M13,7H12v4H5V4H9V3H4V6H1v9h9V12h3ZM9,14H2V7H4v5H9Z" fill="#fff"/>
		<polygon points="11 1 11 2 13.293 2 10.146 5.146 10.854 5.854 14 2.707 14 5 15 5 15 1 11 1" fill="#fff"/>
	</svg>`;
	
	const dockIcon = createElement({elemTag: "div", classList: ['dock'], attrs: {innerHTML: svgDockIcon, title: dockUserPropertiesLabel }});
	const undockIcon = createElement({elemTag: "div", classList: ['undock'], attrs: {innerHTML: svgUndockIcon, title: undockUserPropertiesLabel}});	
	
	const dockActionsContainer = createElement({elemTag: "div", classList: ["dock-icon", "undock"], childNodes: [dockIcon, undockIcon]});

	return [dockActionsContainer, (dockUserInfo) => {
			if (!dockUserInfo){
				dockActionsContainer.classList.add("undock");
			}
			else {
				dockActionsContainer.classList.remove("undock");
			}
	}];
}

function createUserInfo(userName, plantKey, plantName) {
	return [
		createElement({elemTag:'span', attrs: {innerText : userName}}),	
		createElement({elemTag:'span', attrs: {innerText : `${plantKey}: ${plantName}`}})
	];
}

function createUserInfoContainer(userInfo, enableClose, onCloseAction) {
	const exfnContentCanvas = document.querySelector(".exfn-content-canvas");
	if (!exfnContentCanvas) {
		return;
	}
	const childNodes = [...userInfo];
	let closeAction;
	if (enableClose){
		closeAction = createElement({elemTag: "div", attrs:{innerHTML: closeIcon}});
		childNodes.push(closeAction);
	}
	const userInfoContainer = createElement({
		elemTag: "div", 
		classList: ["exfn-floating-user-info"], 
		childNodes
	});
	exfnContentCanvas.appendChild(userInfoContainer);
	
	if (enableClose){
		closeAction.addEventListener("click", onCloseAction);
	}
	return (hideUserInfo) => {
		if (hideUserInfo){
			userInfoContainer.classList.add("hidden");
		}
		else {
			userInfoContainer.classList.remove("hidden");
		}
	};
}

function enhanceUserNavigationWithUserInfo(userMenu, userInfo, dockActions, showDockActions) {
	const childNodes = [createUserAvatar()];
	if (showDockActions){
		childNodes.push(dockActions)
	}
	childNodes.push(...userInfo);
	userMenu.prepend(createElement({
		elemTag: "div",
		classList: ['nav-user-avatar'],
		childNodes
	}));
}
// END EXTRA CODE

/**
 * @param {string} plantName
 * @param {boolean} showUserFullName
 * @param {boolean} showAlwaysUserProps
 * @param {string} plantLabel
 * @param {string} dockUserPropertiesLabel
 * @param {string} undockUserPropertiesLabel
 * @returns {Promise.<void>}
 */
export async function SetUserInfo(plantName, showUserFullName, showAlwaysUserProps, plantLabel, dockUserPropertiesLabel, undockUserPropertiesLabel) {
	// BEGIN USER CODE
	setTimeout(() => {
		let userName = mx.session.getUserName();
		if (showUserFullName){
			const _fullName = mx.session.getUserObject();
			if (_fullName){
				userName = _fullName.get("FullName") || userName;
			}
		}
		const userInfoConfKey = "exfn_mx_show_user_properties";
		const userMenu = document.querySelector('.region-sidebar .mx-navbar.secondary-menu .mx-navbar-submenu');
		const [dockActions, toggleDockAction] = showAlwaysUserProps ? [null, () => {}] :
			createDockActions(dockUserPropertiesLabel, undockUserPropertiesLabel);

		enhanceUserNavigationWithUserInfo(userMenu, createUserInfo(userName, plantLabel, plantName), dockActions, !showAlwaysUserProps);
		
		let toggleUserInfo;
		const initUserInfo =  () => toggleUserInfo = createUserInfoContainer(
			createUserInfo(userName, plantLabel, plantName), 
			!showAlwaysUserProps,
			() => handleUserInfoVisibilityChange(false)
		);
		const handleUserInfoVisibilityChange = (showUserInfo) => {
			toggleDockAction(showUserInfo);	
			toggleUserInfo(!showUserInfo);
			localStorage.setItem(userInfoConfKey, showUserInfo);
		} 
		const existingConfig = localStorage.getItem(userInfoConfKey);
		if (showAlwaysUserProps || (existingConfig && existingConfig === "true")){
			initUserInfo();
		}
		if(!showAlwaysUserProps){
			dockActions.addEventListener("click", (e) => {
				e.preventDefault();
				e.stopPropagation();
				if (!toggleUserInfo){
					initUserInfo(); 
				}
				handleUserInfoVisibilityChange(dockActions.classList.contains("undock"));
			});
		}
	}, 0);
	// END USER CODE
}
