// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_authentication.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the EXFN_Authentication module

	public static java.lang.String getAPPBaseUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EXFN_Authentication.APPBaseUrl");
	}

	public static java.lang.String getAppName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EXFN_Authentication.AppName");
	}

	public static java.lang.String getAppVersion()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EXFN_Authentication.AppVersion");
	}

	public static java.lang.String getClientId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EXFN_Authentication.ClientId");
	}

	public static java.lang.String getPlantId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EXFN_Authentication.PlantId");
	}

	public static java.lang.String getUMCBaseUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EXFN_Authentication.UMCBaseUrl");
	}
}