// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_authentication.proxies;

/**
 * Represents a single OIDC client registration.
 */
public class ClientConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject clientConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXFN_Authentication.ClientConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Alias("Alias"),
		ClientID("ClientID"),
		Active("Active"),
		OpcenterEXFNUrl("OpcenterEXFNUrl"),
		OpcenterUMCUrl("OpcenterUMCUrl"),
		ProjectName("ProjectName"),
		ModelVersion("ModelVersion"),
		PlantId("PlantId"),
		ClientConfiguration_UserRole("EXFN_Authentication.ClientConfiguration_UserRole");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ClientConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject clientConfigurationMendixObject)
	{
		if (clientConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, clientConfigurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.clientConfigurationMendixObject = clientConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static exfn_authentication.proxies.ClientConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new exfn_authentication.proxies.ClientConfiguration(context, mendixObject);
	}

	public static exfn_authentication.proxies.ClientConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return exfn_authentication.proxies.ClientConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<exfn_authentication.proxies.ClientConfiguration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> exfn_authentication.proxies.ClientConfiguration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Alias
	 */
	public final java.lang.String getAlias()
	{
		return getAlias(getContext());
	}

	/**
	 * @param context
	 * @return value of Alias
	 */
	public final java.lang.String getAlias(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alias.toString());
	}

	/**
	 * Set value of Alias
	 * @param alias
	 */
	public final void setAlias(java.lang.String alias)
	{
		setAlias(getContext(), alias);
	}

	/**
	 * Set value of Alias
	 * @param context
	 * @param alias
	 */
	public final void setAlias(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alias)
	{
		getMendixObject().setValue(context, MemberNames.Alias.toString(), alias);
	}

	/**
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID()
	{
		return getClientID(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientID.toString());
	}

	/**
	 * Set value of ClientID
	 * @param clientid
	 */
	public final void setClientID(java.lang.String clientid)
	{
		setClientID(getContext(), clientid);
	}

	/**
	 * Set value of ClientID
	 * @param context
	 * @param clientid
	 */
	public final void setClientID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientid)
	{
		getMendixObject().setValue(context, MemberNames.ClientID.toString(), clientid);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of OpcenterEXFNUrl
	 */
	public final java.lang.String getOpcenterEXFNUrl()
	{
		return getOpcenterEXFNUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of OpcenterEXFNUrl
	 */
	public final java.lang.String getOpcenterEXFNUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OpcenterEXFNUrl.toString());
	}

	/**
	 * Set value of OpcenterEXFNUrl
	 * @param opcenterexfnurl
	 */
	public final void setOpcenterEXFNUrl(java.lang.String opcenterexfnurl)
	{
		setOpcenterEXFNUrl(getContext(), opcenterexfnurl);
	}

	/**
	 * Set value of OpcenterEXFNUrl
	 * @param context
	 * @param opcenterexfnurl
	 */
	public final void setOpcenterEXFNUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String opcenterexfnurl)
	{
		getMendixObject().setValue(context, MemberNames.OpcenterEXFNUrl.toString(), opcenterexfnurl);
	}

	/**
	 * @return value of OpcenterUMCUrl
	 */
	public final java.lang.String getOpcenterUMCUrl()
	{
		return getOpcenterUMCUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of OpcenterUMCUrl
	 */
	public final java.lang.String getOpcenterUMCUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OpcenterUMCUrl.toString());
	}

	/**
	 * Set value of OpcenterUMCUrl
	 * @param opcenterumcurl
	 */
	public final void setOpcenterUMCUrl(java.lang.String opcenterumcurl)
	{
		setOpcenterUMCUrl(getContext(), opcenterumcurl);
	}

	/**
	 * Set value of OpcenterUMCUrl
	 * @param context
	 * @param opcenterumcurl
	 */
	public final void setOpcenterUMCUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String opcenterumcurl)
	{
		getMendixObject().setValue(context, MemberNames.OpcenterUMCUrl.toString(), opcenterumcurl);
	}

	/**
	 * @return value of ProjectName
	 */
	public final java.lang.String getProjectName()
	{
		return getProjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectName
	 */
	public final java.lang.String getProjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectName.toString());
	}

	/**
	 * Set value of ProjectName
	 * @param projectname
	 */
	public final void setProjectName(java.lang.String projectname)
	{
		setProjectName(getContext(), projectname);
	}

	/**
	 * Set value of ProjectName
	 * @param context
	 * @param projectname
	 */
	public final void setProjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectname)
	{
		getMendixObject().setValue(context, MemberNames.ProjectName.toString(), projectname);
	}

	/**
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion()
	{
		return getModelVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelVersion.toString());
	}

	/**
	 * Set value of ModelVersion
	 * @param modelversion
	 */
	public final void setModelVersion(java.lang.String modelversion)
	{
		setModelVersion(getContext(), modelversion);
	}

	/**
	 * Set value of ModelVersion
	 * @param context
	 * @param modelversion
	 */
	public final void setModelVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelversion)
	{
		getMendixObject().setValue(context, MemberNames.ModelVersion.toString(), modelversion);
	}

	/**
	 * @return value of PlantId
	 */
	public final java.lang.String getPlantId()
	{
		return getPlantId(getContext());
	}

	/**
	 * @param context
	 * @return value of PlantId
	 */
	public final java.lang.String getPlantId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlantId.toString());
	}

	/**
	 * Set value of PlantId
	 * @param plantid
	 */
	public final void setPlantId(java.lang.String plantid)
	{
		setPlantId(getContext(), plantid);
	}

	/**
	 * Set value of PlantId
	 * @param context
	 * @param plantid
	 */
	public final void setPlantId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plantid)
	{
		getMendixObject().setValue(context, MemberNames.PlantId.toString(), plantid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ClientConfiguration_UserRole
	 */
	public final system.proxies.UserRole getClientConfiguration_UserRole() throws com.mendix.core.CoreException
	{
		return getClientConfiguration_UserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientConfiguration_UserRole
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.UserRole getClientConfiguration_UserRole(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.UserRole result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ClientConfiguration_UserRole.toString());
		if (identifier != null) {
			result = system.proxies.UserRole.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ClientConfiguration_UserRole
	 * @param clientconfiguration_userrole
	 */
	public final void setClientConfiguration_UserRole(system.proxies.UserRole clientconfiguration_userrole)
	{
		setClientConfiguration_UserRole(getContext(), clientconfiguration_userrole);
	}

	/**
	 * Set value of ClientConfiguration_UserRole
	 * @param context
	 * @param clientconfiguration_userrole
	 */
	public final void setClientConfiguration_UserRole(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.UserRole clientconfiguration_userrole)
	{
		if (clientconfiguration_userrole == null) {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_UserRole.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ClientConfiguration_UserRole.toString(), clientconfiguration_userrole.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return clientConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final exfn_authentication.proxies.ClientConfiguration that = (exfn_authentication.proxies.ClientConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
