// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_authentication.proxies;

public class RefreshSession implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject refreshSessionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXFN_Authentication.RefreshSession";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Expired("Expired"),
		RefreshSession_Session("EXFN_Authentication.RefreshSession_Session");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RefreshSession(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RefreshSession(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject refreshSessionMendixObject)
	{
		if (refreshSessionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, refreshSessionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.refreshSessionMendixObject = refreshSessionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static exfn_authentication.proxies.RefreshSession initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new exfn_authentication.proxies.RefreshSession(context, mendixObject);
	}

	public static exfn_authentication.proxies.RefreshSession load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return exfn_authentication.proxies.RefreshSession.initialize(context, mendixObject);
	}

	/**
	 * @return value of Expired
	 */
	public final java.lang.Boolean getExpired()
	{
		return getExpired(getContext());
	}

	/**
	 * @param context
	 * @return value of Expired
	 */
	public final java.lang.Boolean getExpired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Expired.toString());
	}

	/**
	 * Set value of Expired
	 * @param expired
	 */
	public final void setExpired(java.lang.Boolean expired)
	{
		setExpired(getContext(), expired);
	}

	/**
	 * Set value of Expired
	 * @param context
	 * @param expired
	 */
	public final void setExpired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean expired)
	{
		getMendixObject().setValue(context, MemberNames.Expired.toString(), expired);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RefreshSession_Session
	 */
	public final system.proxies.Session getRefreshSession_Session() throws com.mendix.core.CoreException
	{
		return getRefreshSession_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of RefreshSession_Session
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Session getRefreshSession_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RefreshSession_Session.toString());
		if (identifier != null) {
			result = system.proxies.Session.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RefreshSession_Session
	 * @param refreshsession_session
	 */
	public final void setRefreshSession_Session(system.proxies.Session refreshsession_session)
	{
		setRefreshSession_Session(getContext(), refreshsession_session);
	}

	/**
	 * Set value of RefreshSession_Session
	 * @param context
	 * @param refreshsession_session
	 */
	public final void setRefreshSession_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session refreshsession_session)
	{
		if (refreshsession_session == null) {
			getMendixObject().setValue(context, MemberNames.RefreshSession_Session.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RefreshSession_Session.toString(), refreshsession_session.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return refreshSessionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final exfn_authentication.proxies.RefreshSession that = (exfn_authentication.proxies.RefreshSession) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
