// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_authentication.proxies;

/**
 * An OAuth access token granted by the OIDC provider via the associated ClientConfiguration object.
 */
public class Token implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXFN_Authentication.Token";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Access_token("Access_token"),
		Refresh_token("Refresh_token");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Token(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tokenMendixObject)
	{
		if (tokenMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, tokenMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tokenMendixObject = tokenMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static exfn_authentication.proxies.Token initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new exfn_authentication.proxies.Token(context, mendixObject);
	}

	public static exfn_authentication.proxies.Token load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return exfn_authentication.proxies.Token.initialize(context, mendixObject);
	}

	public static java.util.List<exfn_authentication.proxies.Token> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> exfn_authentication.proxies.Token.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token()
	{
		return getRefresh_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Refresh_token.toString());
	}

	/**
	 * Set value of Refresh_token
	 * @param refresh_token
	 */
	public final void setRefresh_token(java.lang.String refresh_token)
	{
		setRefresh_token(getContext(), refresh_token);
	}

	/**
	 * Set value of Refresh_token
	 * @param context
	 * @param refresh_token
	 */
	public final void setRefresh_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refresh_token)
	{
		getMendixObject().setValue(context, MemberNames.Refresh_token.toString(), refresh_token);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tokenMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final exfn_authentication.proxies.Token that = (exfn_authentication.proxies.Token) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
