// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {boolean} isVisible
 * @returns {Promise.<void>}
 */
export async function ManageButtonsVisibility(isVisible) {
	// BEGIN USER CODE
	
	const existingElements = document.querySelectorAll(".mx-navbar-item");

	const items = Array.from(existingElements)
	.filter(i => i.innerText == "Home" || i.innerText == 'Phone' || i.innerText == 'Client Configuration')
	

	if(isVisible == undefined || isVisible == null || isVisible === true)
	{
		items.forEach((element) => {
				element.style['pointer-events'] = 'auto';
				element.style.opacity = '0.9';
			});
	}
	else{
		items.forEach((element) => {
				element.style['pointer-events'] = 'none';
				element.style.opacity = '0.5';

			});

	}

	// END USER CODE
}
