// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_servicelayer.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the EXFN_ServiceLayer module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder callCommand_MFBuilder(
		java.lang.String _appName,
		java.lang.String _commandName,
		java.lang.String _commandInput
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.CallCommand_MF");
		builder = builder.withParam("AppName", _appName);
		builder = builder.withParam("CommandName", _commandName);
		builder = builder.withParam("CommandInput", _commandInput);
		return builder;
	}

	public static system.proxies.HttpResponse callCommand_MF(
		IContext context,
		java.lang.String _appName,
		java.lang.String _commandName,
		java.lang.String _commandInput
	)
	{
		Object result = callCommand_MFBuilder(
				_appName,
				_commandName,
				_commandInput
			)
			.execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder callCommandWithUniqueParameterBuilder(
		java.lang.String _appName,
		java.lang.String _command,
		java.lang.String _atrribute_Key,
		java.lang.String _attribute_Value
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.CallCommandWithUniqueParameter");
		builder = builder.withParam("AppName", _appName);
		builder = builder.withParam("Command", _command);
		builder = builder.withParam("Atrribute_Key", _atrribute_Key);
		builder = builder.withParam("Attribute_Value", _attribute_Value);
		return builder;
	}

	public static system.proxies.HttpResponse callCommandWithUniqueParameter(
		IContext context,
		java.lang.String _appName,
		java.lang.String _command,
		java.lang.String _atrribute_Key,
		java.lang.String _attribute_Value
	)
	{
		Object result = callCommandWithUniqueParameterBuilder(
				_appName,
				_command,
				_atrribute_Key,
				_attribute_Value
			)
			.execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createLocalMxODataConfigurationBuilder(
		java.lang.String _odataEndpoint
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.CreateLocalMxODataConfiguration");
		builder = builder.withParam("OdataEndpoint", _odataEndpoint);
		return builder;
	}

	public static system.proxies.ConsumedODataConfiguration createLocalMxODataConfiguration(
		IContext context,
		java.lang.String _odataEndpoint
	)
	{
		Object result = createLocalMxODataConfigurationBuilder(
				_odataEndpoint
			)
			.execute(context);
		return result == null ? null : system.proxies.ConsumedODataConfiguration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createRuntimeODataConfigurationBuilder(
		java.lang.String _foundationAppName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.CreateRuntimeODataConfiguration");
		builder = builder.withParam("FoundationAppName", _foundationAppName);
		return builder;
	}

	public static system.proxies.ConsumedODataConfiguration createRuntimeODataConfiguration(
		IContext context,
		java.lang.String _foundationAppName
	)
	{
		Object result = createRuntimeODataConfigurationBuilder(
				_foundationAppName
			)
			.execute(context);
		return result == null ? null : system.proxies.ConsumedODataConfiguration.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AvailableRuntimeUIApplicationsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.DS_AvailableRuntimeUIApplications");
		return builder;
	}

	public static java.util.List<exfn_servicelayer.proxies.UIApplicationsPerPlantItem> dS_AvailableRuntimeUIApplications(IContext context)
	{
		Object result = dS_AvailableRuntimeUIApplicationsBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> exfn_servicelayer.proxies.UIApplicationsPerPlantItem.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetApplicationURLBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.DS_GetApplicationURL");
		return builder;
	}

	public static exfn_servicelayer.proxies.UIApplication dS_GetApplicationURL(IContext context)
	{
		Object result = dS_GetApplicationURLBuilder().execute(context);
		return result == null ? null : exfn_servicelayer.proxies.UIApplication.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder errorHandling_ConsumedODataServiceBuilder(
		system.proxies.HttpResponse _httpResponse
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.ErrorHandling_ConsumedODataService");
		builder = builder.withParam("httpResponse", _httpResponse);
		return builder;
	}

	public static java.lang.String errorHandling_ConsumedODataService(
		IContext context,
		system.proxies.HttpResponse _httpResponse
	)
	{
		Object result = errorHandling_ConsumedODataServiceBuilder(
				_httpResponse
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder execute_OData_ReadingFunctionBuilder(
		system.proxies.HttpRequest _httpRequest,
		system.proxies.ODataResponse _oDataResponse,
		java.lang.String _appName,
		java.lang.String _functionName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.Execute_OData_ReadingFunction");
		builder = builder.withParam("HttpRequest", _httpRequest);
		builder = builder.withParam("ODataResponse", _oDataResponse);
		builder = builder.withParam("AppName", _appName);
		builder = builder.withParam("FunctionName", _functionName);
		return builder;
	}

	public static system.proxies.HttpResponse execute_OData_ReadingFunction(
		IContext context,
		system.proxies.HttpRequest _httpRequest,
		system.proxies.ODataResponse _oDataResponse,
		java.lang.String _appName,
		java.lang.String _functionName
	)
	{
		Object result = execute_OData_ReadingFunctionBuilder(
				_httpRequest,
				_oDataResponse,
				_appName,
				_functionName
			)
			.execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, (IMendixObject) result);
	}
	/**
	 * Nanoflow to execute an OData query on the Engineering endpoint.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder executeEngineeringQuery_MFBuilder(
		java.lang.String _entityName,
		java.lang.String _queryString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.ExecuteEngineeringQuery_MF");
		builder = builder.withParam("EntityName", _entityName);
		builder = builder.withParam("QueryString", _queryString);
		return builder;
	}

	/**
	 * Nanoflow to execute an OData query on the Engineering endpoint.
	 */
	public static system.proxies.HttpResponse executeEngineeringQuery_MF(
		IContext context,
		java.lang.String _entityName,
		java.lang.String _queryString
	)
	{
		Object result = executeEngineeringQuery_MFBuilder(
				_entityName,
				_queryString
			)
			.execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder executeFunction_MFBuilder(
		java.lang.String _appName,
		java.lang.String _functionName,
		java.lang.String _functionFilter,
		java.lang.Long _top,
		java.lang.Long _skip
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.ExecuteFunction_MF");
		builder = builder.withParam("AppName", _appName);
		builder = builder.withParam("FunctionName", _functionName);
		builder = builder.withParam("FunctionFilter", _functionFilter);
		builder = builder.withParam("Top", _top);
		builder = builder.withParam("Skip", _skip);
		return builder;
	}

	public static system.proxies.HttpResponse executeFunction_MF(
		IContext context,
		java.lang.String _appName,
		java.lang.String _functionName,
		java.lang.String _functionFilter,
		java.lang.Long _top,
		java.lang.Long _skip
	)
	{
		Object result = executeFunction_MFBuilder(
				_appName,
				_functionName,
				_functionFilter,
				_top,
				_skip
			)
			.execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder executeQuery_MFBuilder(
		java.lang.String _appName,
		java.lang.String _entityName,
		java.lang.String _queryString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.ExecuteQuery_MF");
		builder = builder.withParam("AppName", _appName);
		builder = builder.withParam("EntityName", _entityName);
		builder = builder.withParam("QueryString", _queryString);
		return builder;
	}

	public static system.proxies.HttpResponse executeQuery_MF(
		IContext context,
		java.lang.String _appName,
		java.lang.String _entityName,
		java.lang.String _queryString
	)
	{
		Object result = executeQuery_MFBuilder(
				_appName,
				_entityName,
				_queryString
			)
			.execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getFile_MFBuilder(
		java.lang.String _appName,
		java.lang.String _field
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.GetFile_MF");
		builder = builder.withParam("AppName", _appName);
		builder = builder.withParam("Field", _field);
		return builder;
	}

	public static exfn_servicelayer.proxies.ExFnDocument getFile_MF(
		IContext context,
		java.lang.String _appName,
		java.lang.String _field
	)
	{
		Object result = getFile_MFBuilder(
				_appName,
				_field
			)
			.execute(context);
		return result == null ? null : exfn_servicelayer.proxies.ExFnDocument.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getPublicGroupsBuilder(
		java.lang.String _queryString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.GetPublicGroups");
		builder = builder.withParam("QueryString", _queryString);
		return builder;
	}

	public static java.util.List<exfn_servicelayer.proxies.PublicGroup> getPublicGroups(
		IContext context,
		java.lang.String _queryString
	)
	{
		Object result = getPublicGroupsBuilder(
				_queryString
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> exfn_servicelayer.proxies.PublicGroup.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getPublicRolesBuilder(
		java.lang.String _queryString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.GetPublicRoles");
		builder = builder.withParam("QueryString", _queryString);
		return builder;
	}

	public static java.util.List<exfn_servicelayer.proxies.PublicRole> getPublicRoles(
		IContext context,
		java.lang.String _queryString
	)
	{
		Object result = getPublicRolesBuilder(
				_queryString
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> exfn_servicelayer.proxies.PublicRole.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getPublicUsersBuilder(
		java.lang.String _queryString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.GetPublicUsers");
		builder = builder.withParam("QueryString", _queryString);
		return builder;
	}

	public static java.util.List<exfn_servicelayer.proxies.PublicUser> getPublicUsers(
		IContext context,
		java.lang.String _queryString
	)
	{
		Object result = getPublicUsersBuilder(
				_queryString
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> exfn_servicelayer.proxies.PublicUser.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder handleBadRequestBuilder(
		system.proxies.HttpResponse _httpResponse
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.HandleBadRequest");
		builder = builder.withParam("HttpResponse", _httpResponse);
		return builder;
	}

	public static exfn_servicelayer.proxies.HttpError handleBadRequest(
		IContext context,
		system.proxies.HttpResponse _httpResponse
	)
	{
		Object result = handleBadRequestBuilder(
				_httpResponse
			)
			.execute(context);
		return result == null ? null : exfn_servicelayer.proxies.HttpError.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_ExecuteFunctionOdata_MFBuilder(
		java.lang.String _appName,
		java.lang.String _functionName,
		exfn_servicelayer.proxies.RF_RequestParameters _rF_RequestParameters,
		system.proxies.ODataResponse _oDataResponse,
		system.proxies.HttpRequest _httpRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.SUB_ExecuteFunctionOdata_MF");
		builder = builder.withParam("AppName", _appName);
		builder = builder.withParam("FunctionName", _functionName);
		builder = builder.withParam("RF_RequestParameters", _rF_RequestParameters);
		builder = builder.withParam("ODataResponse", _oDataResponse);
		builder = builder.withParam("HttpRequest", _httpRequest);
		return builder;
	}

	public static system.proxies.HttpResponse sUB_ExecuteFunctionOdata_MF(
		IContext context,
		java.lang.String _appName,
		java.lang.String _functionName,
		exfn_servicelayer.proxies.RF_RequestParameters _rF_RequestParameters,
		system.proxies.ODataResponse _oDataResponse,
		system.proxies.HttpRequest _httpRequest
	)
	{
		Object result = sUB_ExecuteFunctionOdata_MFBuilder(
				_appName,
				_functionName,
				_rF_RequestParameters,
				_oDataResponse,
				_httpRequest
			)
			.execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_ParseRF_OdataParametersBuilder(
		system.proxies.HttpRequest _httpRequest,
		system.proxies.ODataResponse _oDataResponse
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("EXFN_ServiceLayer.SUB_ParseRF_OdataParameters");
		builder = builder.withParam("HttpRequest", _httpRequest);
		builder = builder.withParam("ODataResponse", _oDataResponse);
		return builder;
	}

	public static exfn_servicelayer.proxies.RF_RequestParameters sUB_ParseRF_OdataParameters(
		IContext context,
		system.proxies.HttpRequest _httpRequest,
		system.proxies.ODataResponse _oDataResponse
	)
	{
		Object result = sUB_ParseRF_OdataParametersBuilder(
				_httpRequest,
				_oDataResponse
			)
			.execute(context);
		return result == null ? null : exfn_servicelayer.proxies.RF_RequestParameters.initialize(context, (IMendixObject) result);
	}
}
