// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package exfn_servicelayer.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CallCommandAction extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String AppName;
	private final java.lang.String CommandName;
	private final java.lang.String ExportUsing;
	private final IMendixObject Input;

	public CallCommandAction(
		IContext context,
		java.lang.String _appName,
		java.lang.String _commandName,
		java.lang.String _exportUsing,
		IMendixObject _input
	)
	{
		super(context);
		this.AppName = _appName;
		this.CommandName = _commandName;
		this.ExportUsing = _exportUsing;
		this.Input = _input;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CallCommandAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
