// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package exfn_crossnavigation.proxies;

public class ScreenConfig implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject screenConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EXFN_CrossNavigation.ScreenConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UIAppName("UIAppName"),
		ScreenId("ScreenId"),
		Params("Params"),
		IsMDUI("IsMDUI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ScreenConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ScreenConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject screenConfigMendixObject)
	{
		if (screenConfigMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, screenConfigMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.screenConfigMendixObject = screenConfigMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static exfn_crossnavigation.proxies.ScreenConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new exfn_crossnavigation.proxies.ScreenConfig(context, mendixObject);
	}

	public static exfn_crossnavigation.proxies.ScreenConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return exfn_crossnavigation.proxies.ScreenConfig.initialize(context, mendixObject);
	}

	/**
	 * @return value of UIAppName
	 */
	public final java.lang.String getUIAppName()
	{
		return getUIAppName(getContext());
	}

	/**
	 * @param context
	 * @return value of UIAppName
	 */
	public final java.lang.String getUIAppName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UIAppName.toString());
	}

	/**
	 * Set value of UIAppName
	 * @param uiappname
	 */
	public final void setUIAppName(java.lang.String uiappname)
	{
		setUIAppName(getContext(), uiappname);
	}

	/**
	 * Set value of UIAppName
	 * @param context
	 * @param uiappname
	 */
	public final void setUIAppName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uiappname)
	{
		getMendixObject().setValue(context, MemberNames.UIAppName.toString(), uiappname);
	}

	/**
	 * @return value of ScreenId
	 */
	public final java.lang.String getScreenId()
	{
		return getScreenId(getContext());
	}

	/**
	 * @param context
	 * @return value of ScreenId
	 */
	public final java.lang.String getScreenId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScreenId.toString());
	}

	/**
	 * Set value of ScreenId
	 * @param screenid
	 */
	public final void setScreenId(java.lang.String screenid)
	{
		setScreenId(getContext(), screenid);
	}

	/**
	 * Set value of ScreenId
	 * @param context
	 * @param screenid
	 */
	public final void setScreenId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String screenid)
	{
		getMendixObject().setValue(context, MemberNames.ScreenId.toString(), screenid);
	}

	/**
	 * @return value of Params
	 */
	public final java.lang.String getParams()
	{
		return getParams(getContext());
	}

	/**
	 * @param context
	 * @return value of Params
	 */
	public final java.lang.String getParams(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Params.toString());
	}

	/**
	 * Set value of Params
	 * @param params
	 */
	public final void setParams(java.lang.String params)
	{
		setParams(getContext(), params);
	}

	/**
	 * Set value of Params
	 * @param context
	 * @param params
	 */
	public final void setParams(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String params)
	{
		getMendixObject().setValue(context, MemberNames.Params.toString(), params);
	}

	/**
	 * @return value of IsMDUI
	 */
	public final java.lang.Boolean getIsMDUI()
	{
		return getIsMDUI(getContext());
	}

	/**
	 * @param context
	 * @return value of IsMDUI
	 */
	public final java.lang.Boolean getIsMDUI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsMDUI.toString());
	}

	/**
	 * Set value of IsMDUI
	 * @param ismdui
	 */
	public final void setIsMDUI(java.lang.Boolean ismdui)
	{
		setIsMDUI(getContext(), ismdui);
	}

	/**
	 * Set value of IsMDUI
	 * @param context
	 * @param ismdui
	 */
	public final void setIsMDUI(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ismdui)
	{
		getMendixObject().setValue(context, MemberNames.IsMDUI.toString(), ismdui);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return screenConfigMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final exfn_crossnavigation.proxies.ScreenConfig that = (exfn_crossnavigation.proxies.ScreenConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
